# SPDX-License-Identifier: 0BSD

name: Check C/C++ files with clang-format

on: push

jobs:
  ubuntu:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: clang-format lint
        uses: DoozyX/clang-format-lint-action@v0.18.1
